server:
  port: 4000
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/entrelibros
    username: postgres
    password: ${SQL_PASS:${spring.datasource.password}}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET:${jwt.secret}}
  issuer: "https://entrelibros.app"
  accessTtl: PT15M
